version: "3.8"

services:
  mongodb:
    image: mongo:4.2.6
    container_name: hello-docker-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app

  app:
    container_name: hello-docker-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - mongodb.uri=mongodb://root:password@mongodb:27017
    ports:
      - "9091:8080"
    networks:
      - app
    depends_on:
      - mongodb

volumes:
  mongodb_volume:

networks:
  app:
